global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "invaders-bot"
    scheme: https
    static_configs:
      - targets: ["invadersbot-production.up.railway.app"]
    metrics_path: /metrics

  - job_name: "invaders-consumer"
    scheme: https
    static_configs:
      - targets: ["consumer.flashcastr.app"]
    metrics_path: /metrics
