global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "invaders-bot"
    static_configs:
      - targets: ["${INVADERS_BOT_TARGET}"]
    metrics_path: /metrics

  - job_name: "invaders-consumer"
    scheme: https
    static_configs:
      - targets: ["${INVADERS_CONSUMER_TARGET}"]
    metrics_path: /metrics

  - job_name: "flashcastr-api"
    scheme: https
    static_configs:
      - targets: ["${FLASHCASTR_API_TARGET}"]
    metrics_path: /metrics
